#!/bin/bash
if [ -f paster.pid ]; then
    kill $(cat paster.pid)
fi
if [ -f orbited.pid ]; then
    kill $(cat orbited.pid)
fi
if [ -f hub.pid ]; then
    kill $(cat hub.pid)
fi
if [ -f memcached.pid ]; then
    kill $(cat memcached.pid)
fi
rm -f *.pid
