#!/bin/bash -e
export LOG=logs/orbited.log

echo "-------------- Trying to start up --------------" >> $LOG
if test -z "$1"
then
        echo "No virtualenv argument supplied.  Aborting." >> $LOG
        exit 1
else
        echo "Using virtualenv $1" >> $LOG
fi

if test -z "$VIRTUAL_ENV"
then
        source $WORKON_HOME/$1/bin/activate
fi
orbited -c orbited.cfg >> $LOG 2>&1 < /dev/null &
echo $! > orbited.pid

exit 0
