#!/bin/bash -e
source ~/.bashrc
export LOG=logs/paster.log

echo "-------------- Trying to start up --------------" >> $LOG
if test -z "$1"
then
        echo "No virtualenv argument supplied.  Aborting." >> $LOG
        exit 1
else
        echo "Using virtualenv $1" >> $LOG
fi
source $WORKON_HOME/$1/bin/activate
paster serve development.ini >> logs/paster.log 2>&1 < /dev/null &
echo $! > paster.pid
exit 0
